# reload configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1              # start indexing windows at 1 instead of 0
setw -g mode-keys vi             #enables Vim-style keybindings in tmux modes
set -g set-clipboard on          # use system clipboard
set -g renumber-windows on             # start indexing windows at 1 instead of 0
set -g status-position top       # macOS / darwin style


set -g prefix C-t                # set leader key as control + t
set -g mouse on                  # allows mouse usage for tab resize


# vim motions for tabs
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# catppuccin configuration
set -g @catppuccin_flavor "mocha"

set -g @catppuccin_application_color "#{@thm_yellow}"
set -g @catppuccin_directory_color "#{@thm_sapphire}"
set -g @catppuccin_session_color "#{?client_prefix,#{@thm_mauve},#{@thm_green}}"

set -g @catppuccin_session_icon " "  
set -g @catppuccin_directory_icon "󰉋 "
set -g @catppuccin_application_icon " "

set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_background "#{@thm_bg}"

set -g status-left ""
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_directory} #{E:@catppuccin_status_session}"

run '~/.config/tmux/plugins/tpm/tpm'
